---
version: "3"
services:
 devopsdb:
   image: srinuas/myreponew:db
   ports:
     - "123:3306"

 application:
   image: srinuas/myreponew:ap
   ports:
     - "1111:8080"
   depends_on:
     - "devopsdb"
